### ISSUE TITLE
v2.0.0 ideas

### ISSUE THREAD

**Issue by ryardley** [ryardley/indexr#17]
# Indexr v2.0.0 spec

I would like this comment to act as a spec for version 2. 

If you have any comments or suggestions please add them below and I will incorporate them into this comment.

**Comment by ryardley** [comment]
For version 2, I want to look at some of the common things I am seeing related to indexes. 

I am seeing quite a lot of this from libraries: 

```javascript
import flatten from 'lodash/flatten';
```
whilst you can also do

```javascript
import {flatten} from 'lodash';
```

as well as

```javascript
import _ from 'lodash';

_.flatten(fooArray);
```

**Comment by ryardley** [comment]
The `create-index` package uses it's own header to work out if it is allowed to overwrite a file or now. I think this should be built in but not as a string as a comment of some sort.

```javascript
/* indexr autogenerated file */
... rest of the file 
```

**Comment by ryardley** [comment]
- [ ] Configure using .indexrc.js (https://github.com/ryardley/indexr/issues/12)
- [ ] Exporting index files for libraries (https://github.com/ryardley/indexr/issues/23)
- [ ] Header comments signal write override (https://github.com/ryardley/indexr/issues/24)
- [ ] Use custom named collections from header comments (https://github.com/ryardley/indexr/issues/25)

**Comment by ryardley** [comment]
Closing this as flagging tasks for v2 is not in the spirit of semver
